# Generated by Django 5.0.9 on 2024-11-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ime')),
                ('email', models.EmailField(max_length=254, verbose_name='Email naslov')),
            ],
        ),
    ]
