# Generated by Django 5.0.9 on 2024-11-10 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Prejeto'),
            preserve_default=False,
        ),
    ]
