# Generated by Django 5.0.9 on 2024-11-10 13:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_reason',
            field=models.CharField(blank=True, max_length=50, verbose_name='Razlog'),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Sporočilo'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Izdelek'),
        ),
    ]
