# Generated by Django 5.0.9 on 2024-10-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
