# Generated by Django 5.0.9 on 2024-10-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationSettings',
            new_name='SocialSettings',
        ),
    ]
