# Generated by Django 5.0.9 on 2024-11-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_personalsettings_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
