# Generated by Django 5.0.9 on 2024-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
    ]
