# Generated by Django 5.0.9 on 2024-11-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_socialsettings_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialSettings',
            new_name='PersonalSettings',
        ),
    ]
