# Generated by Django 5.0.9 on 2024-11-01 18:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_personalsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalsettings',
            name='workshop_address',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Naslov delavnice'),
        ),
    ]
