# Generated by Django 5.0.9 on 2024-11-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_personalsettings_workshop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsettings',
            name='workshop_address_raw',
            field=models.CharField(blank=True, max_length=100, verbose_name='Naslov delavnice brez novih vrstic'),
        ),
    ]
