# Generated by Django 5.0.9 on 2024-11-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_factcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcard',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Opis'),
        ),
    ]
