# Generated by Django 5.0.9 on 2024-11-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutpage_intro_heading_aboutpage_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='intro_heading',
            field=models.CharField(blank=True, max_length=30, verbose_name='Naslov uvoda'),
        ),
    ]
