# Generated by Django 5.0.9 on 2024-10-28 21:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='image_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
