# Generated by Django 5.0.9 on 2024-11-08 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibition.productcategory'),
        ),
    ]
