# Generated by Django 5.0.9 on 2024-11-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_alter_galleryimages_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exhibition.productcategory'),
        ),
    ]
