# Generated by Django 5.0.9 on 2024-11-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0006_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='sort_order',
        ),
    ]
