# Generated by Django 5.0.9 on 2024-11-08 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0007_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exhibition.productcategory'),
        ),
    ]
