# Generated by Django 5.0.9 on 2024-11-08 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0008_alter_galleryimages_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimages',
            name='knife_model',
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exhibition.productcategory', verbose_name='Kategorija'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Primer: kuhinjski noz, lovski noz,...', max_length=20, verbose_name='Ime kategorije'),
        ),
    ]
