# Generated by Django 5.0.9 on 2024-11-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0009_remove_galleryimages_knife_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='super_category',
            field=models.CharField(blank=True, help_text='Primer: nož, obesek,...', max_length=20, verbose_name='Ime nad-kategorije'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(help_text='Primer: kuhinjski noz, lovski noz,...', max_length=20, verbose_name='Ime kategorije'),
        ),
    ]
