# Generated by Django 5.0.9 on 2024-11-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0011_alter_productcategory_super_category'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='heading',
            field=models.CharField(blank=True, max_length=50, verbose_name='Naslov'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Slika ozadja, za naslovom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Glavna slika'),
        ),
    ]
