# Generated by Django 5.0.9 on 2024-11-10 13:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0012_gallerypage_heading_gallerypage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='image_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Kratek opis'),
        ),
    ]
