# Generated by Django 5.0.9 on 2024-11-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0013_alter_galleryimages_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='name',
            field=models.CharField(default='Noz', help_text='To ni isto kot kategorija (pravilno: Lovski noz iz kaljenega jekla)', max_length=100, verbose_name='Ime noza'),
            preserve_default=False,
        ),
    ]
