# Generated by Django 5.0.9 on 2024-11-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0016_remove_pageimage_page_remove_pageimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='page',
        ),
    ]
