# Generated by Django 5.0.9 on 2024-11-10 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0017_remove_galleryimage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 10, 21, 30, 49, 710959, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
