# Generated by Django 5.0.9 on 2024-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0019_remove_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryactualimage',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryactualimage',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
