# Generated by Django 5.0.9 on 2024-10-28 22:18

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=50, verbose_name='Naslov')),
                ('hero_small_text', models.CharField(blank=True, max_length=50, verbose_name='Podnaslov')),
                ('cta_title', models.CharField(blank=True, max_length=50, verbose_name='CTA - naslov')),
                ('cta_small_text', wagtail.fields.RichTextField(blank=True, verbose_name='CTA - opis')),
                ('cta_btn_text', models.CharField(blank=True, max_length=20, verbose_name='CTA - gumb')),
                ('cta_btn_destination', models.CharField(blank=True, max_length=20, verbose_name='CTA - gumb destinacija')),
                ('gallery_title', models.CharField(blank=True, max_length=50, verbose_name='Galerija - naslov')),
                ('gallery_description', wagtail.fields.RichTextField(blank=True, verbose_name='Galerija - opis')),
                ('gallery_btn_label', models.CharField(blank=True, max_length=10, verbose_name='Galerija - napis v gumbu')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HeroLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('destination', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_sidebar_links', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=20)),
                ('description', wagtail.fields.RichTextField()),
                ('btn_label', models.CharField(max_length=20)),
                ('btn_destination', models.CharField(max_length=20)),
                ('knife_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_feature_card', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
