# Generated by Django 5.0.9 on 2024-10-29 11:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='O meni - kratek opis'),
        ),
    ]
